name: WordWise CI/CD

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

env:
 AWS_REGION: ap-northeast-2

jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read

   steps:
   - uses: actions/checkout@v4
   
   - name: Set up JDK 21
     uses: actions/setup-java@v4
     with:
       java-version: '21'
       distribution: 'temurin'

   - name: Setup Gradle
     uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
     
   - name: Build with Gradle
     run: ./gradlew clean build

   - name: Upload build artifacts
     uses: actions/upload-artifact@v4
     with:
       name: build-artifacts
       path: build/libs/*.jar
       retention-days: 5

   - name: Set up SSH
     run: |
       mkdir -p ~/.ssh
       echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa
       ssh-keyscan -H ec2-3-35-49-212.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

   - name: Deploy to EC2
     run: |
       scp -i ~/.ssh/id_rsa build/libs/*.jar ec2-user@ec2-3-35-49-212.ap-northeast-2.compute.amazonaws.com:~/app/
       ssh -i ~/.ssh/id_rsa ec2-user@ec2-3-35-49-212.ap-northeast-2.compute.amazonaws.com << 'EOF'
         cd ~/app
         docker stop wordwise || true
         docker rm wordwise || true
         docker build -t wordwise .
         docker run -d --name wordwise -p 8081:8081 wordwise
       EOF

 dependency-submission:
   runs-on: ubuntu-latest
   permissions:
     contents: write

   steps:
   - uses: actions/checkout@v4
   - name: Set up JDK 21
     uses: actions/setup-java@v4
     with:
       java-version: '21'
       distribution: 'temurin'

   - name: Generate and submit dependency graph
     uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
