name: WordWise CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Gradle Wrapper 검증 단계 추가
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    # Gradle 캐시 설정 추가
    - name: Setup Gradle Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Print Gradle Version and Project Structure
      run: |
        ./gradlew --version
        ls -la
        pwd
        
    - name: Build with Gradle (Verbose)
      run: |
        ./gradlew clean build --stacktrace --info --debug

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/*.jar
        retention-days: 5

    - name: Set up SSH
      if: success()
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ec2-15-164-97-231.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/id_rsa build/libs/*.jar manager@ec2-15-164-97-231.ap-northeast-2.compute.amazonaws.com:~/app/
        scp -i ~/.ssh/id_rsa deploy.sh manager@ec2-15-164-97-231.ap-northeast-2.compute.amazonaws.com:~/app/
        ssh -i ~/.ssh/id_rsa manager@ec2-15-164-97-231.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd ~/app
          chmod +x deploy.sh
          ./deploy.sh
        EOF
